let data = [
    {
        key: 1,
        title: '为什么生气运动，左下腹结肠位置疼痛',
        keyword:'生气运动，结肠位置疼痛',
        asknumber: 20,
        status: '未采纳',
        updatetime: '3个月前'
    }, {
        key: 2,
        title: '布地奈德福莫特罗粉吸入剂，不确定是否吸多',
        keyword: '布地奈德福莫特罗粉，吸多',
        asknumber: 3,
        status: '未采纳',
        updatetime: '4个月前'
    }, {
        key: 3,
        title: '宝宝脸上长痘痘怎么办？',
        keyword: '脸上长痘痘',
        asknumber: 10,
        status: '未采纳',
        updatetime: '5个月前'
    }, {
        key: 4,
        title: '孩子咳嗽严重查血后结果',
        keyword: '咳嗽严重查血',
        asknumber: 13,
        status: '未采纳',
        updatetime: '3天前'
    }, {
        key: 5,
        title: '哮喘减轻用药量，已经半年未发生哮喘症状',
        keyword: '哮喘减轻用药量',
        asknumber: 34,
        status: '未采纳',
        updatetime: '3个小时前'
    }, {
        key: 6,
        title: '肺部积水，不吃不喝。',
        keyword: '肺部积水',
        asknumber: 13,
        status: '未采纳',
        updatetime: '5个月前'
    }, {
        key: 7,
        title: '变异性哮喘会有清涕吗？中途会不会好几天都',
        keyword: '变异性哮喘',
        asknumber: 20,
        status: '未采纳',
        updatetime: '3个月前'
    }, {
        key: 8,
        keyword: '咳嗽',
        title: '咳嗽都是夜里12点左右咳嗽',
        asknumber: 20,
        status: '未采纳',
        updatetime: '3个月前'
    }, {
        key: 9,
        title: '慢性肺阻塞，医生说三分之二肺阻塞',
        keyword: '慢性肺阻塞',
        asknumber: 20,
        status: '未采纳',
        updatetime: '3个月前'
    }, {
        key: 10,
        title: '做了支气管激发试验后胸部难受',
        keyword: '支气管激发试验',
        asknumber: 20,
        status: '未采纳',
        updatetime: '3个月前'
    }, {
        key: 11,
        title: '怎么检查自己有无哮喘',
        keyword: '有无哮喘',
        asknumber: 22,
        status: '未采纳',
        updatetime: '3个月前'
    }, {
        key: 12,
        title: '去年12月在医院诊断为哮喘，用孟鲁司特钠',
        keyword: '孟鲁司特钠',
        asknumber: 20,
        status: '未采纳',
        updatetime: '3个月前'
    }, {
        key: 13,
        title: '布地奈德吸入气雾剂的用法用量 ',
        keyword: '布地奈德吸入气雾剂的用法用量',
        asknumber: 20,
        status: '未采纳',
        updatetime: '3个月前'
    }, {
        key: 14,
        title: '我咳嗽有两个月了，大夫',
        keyword: '咳嗽',
        asknumber: 20,
        status: '未采纳',
        updatetime: '3个月前'
    }, {
        key: 15,
        title: '哮喘刚好在路上吸灰尘',
        keyword: '哮喘刚好在路上吸灰尘',
        asknumber: 20,
        status: '未采纳',
        updatetime: '3个月前'
    }, {
        key: 16,
        keyword: '胸闷两周',
        title: '胸闷两周帮我看看化验单',
        asknumber: 20,
        status: '未采纳',
        updatetime: '3个月前'
    }, {
        key: 17,
        keyword: '食疗秘方',
        title: '治疗哮喘的食疗秘方，自然发酵的鲜果酒，喝',
        asknumber: 20,
        status: '未采纳',
        updatetime: '3个月前'
    }, {
        key: 18,
        keyword: '蚂蚁，驱除',
        title: '衣柜里有蚂蚁，缝隙中也有蚂蚁，怎么驱除',
        asknumber: 20,
        status: '未采纳',
        updatetime: '3个月前'
    }, {
        key: 19,
        keyword: '一见风就咳嗽',
        title: '生完孩子21天，一见风就咳嗽',
        asknumber: 20,
        status: '未采纳',
        updatetime: '3个月前'
    }
];

export default data;